### ISSUE TITLE
Cant create arena

### ISSUE THREAD

**Issue by BLABLA2003** [jerzean/UltimateSurvivalGames#3]
Every time i try to create an arena it says an internal error occurred. I will add the log.

1.16.1 paper-134
plugins:
asyncworldedit3.7.5
bentobox 1.14.2
essentialsX 2.18.0.0
luck-perms 5.1.26
multiverse:
core 4.1.0
inventories 3.0.0
netherPortals 4.1.0
sign portals 4.1.0
PvP1vs1 1.7.1
Vault
world edit 7.2.0 beta3

**Comment by BLABLA2003** [comment]
[10:04:21] [Server thread/INFO]: BLABLA03 issued server command: /sg arena create lobby1 arena1
[10:04:21] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sg' in plugin SurvivalGames v1.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at me.maker56.survivalgames.arena.ArenaManager.createArena(ArenaManager.java:339) ~[?:?]
	at me.maker56.survivalgames.commands.arguments.ArenaArgument.execute(ArenaArgument.java:65) ~[?:?]
	at me.maker56.survivalgames.commands.CommandSG.onCommand(CommandSG.java:86) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-134]
	... 18 more

**Comment by jerzean** [comment]
let me do some digging an figure this out

**Comment by jerzean** [comment]
@BLABLA2003  ok so my findings are this  the newest version of world edit (7.2.0-beta3) isnt compatible with with the newest Async World edit something changed in one of them an it has nothing to do with my plugin
Use this version of Worldedit  its (7.2.0-beta2)
https://builds.enginehub.org/job/worldedit/14969

**Comment by BLABLA2003** [comment]
OK, I will try, thanks very much!

**Comment by BLABLA2003** [comment]
Hi! For me the error still persists! I have read the thread on saving an arena and used what you recommended there but it still dosent work. From what i can tell the error log is the same but i will still add here.
[10:31:07 INFO]: BLABLA03 issued server command: /sg arena create lobby1 arena1
[10:31:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sg' in plugin SurvivalGames v1.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1260) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
	at me.maker56.survivalgames.arena.ArenaManager.createArena(ArenaManager.java:339) ~[?:?]
	at me.maker56.survivalgames.commands.arguments.ArenaArgument.execute(ArenaArgument.java:65) ~[?:?]
	at me.maker56.survivalgames.commands.CommandSG.onCommand(CommandSG.java:86) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-134]
	... 18 more
and the entire log
[latest.log](https://github.com/jerzean/UltimateSurvivalGames/files/5088913/latest.log)

**Comment by dotI0** [comment]
Dumb question but I had the same error…
Do you have selected the Arena with WorldEdit before creating the arena??

**Comment by BLABLA2003** [comment]
No i havent as i considered that the entire world will became the arena , i will try.

**Comment by jerzean** [comment]
You must select the area with world edit.  Please watch the video posted at the bottom of the plugin page on spigot
