### ISSUE TITLE
Cant Save Arena

### ISSUE THREAD

**Issue by dotI0** [jerzean/UltimateSurvivalGames#4]
Every time I want to try to save an Arena with /sg arena save the following Error occurs.

`[16:40:06 INFO]: xManInWhitex issued server command: /sg arena save
[16:40:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sg' in plugin SurvivalGames v1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at me.maker56.survivalgames.arena.ArenaManager.save(ArenaManager.java:69) ~[?:?]
        at me.maker56.survivalgames.commands.arguments.ArenaArgument.execute(ArenaArgument.java:53) ~[?:?]
        at me.maker56.survivalgames.commands.CommandSG.onCommand(CommandSG.java:86) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-135]
        ... 18 more
`

What can I do?

**Comment by jerzean** [comment]
ill look at it when i get home from work

**Comment by jerzean** [comment]
@xManInWhitex What plugins are installed an whats there versions?

**Comment by jerzean** [comment]
@xManInWhitex  ok so my findings are this 

the newest version of world edit (7.2.0-beta3) isnt compatible with with the newest Async World edit something changed in one of them an it has nothing to do with my plugin
Use this version of Worldedit its (7.2.0-beta2)
https://builds.enginehub.org/job/worldedit/14969

**Comment by dotI0** [comment]
I'm using Beta 2 of WE because of the incompatibility to Async WE.
I've attached the full server log.

Full Server Log: https://pastebin.com/f4bHrfzG

**Comment by dotI0** [comment]
The latest Version of Async World Edit (3.7.6) is compatible with WE 7.2.0beta3.
If tested AWE 3.7.6 with WE 7.2.0-beta3 and AWE 3.7.5 with WE 7.2.0-beta2.
None of these combinations are working. AWE 3.7.6 isn't compatible with WE 7.2.0-beta2.

**Comment by jerzean** [comment]
the only thing i can see thats is causing the couple errors in the console from UltServivalGames is due to legacy plugin support being enabled
`[11:59:56] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!`

the only thing i know to tell you is to disable each plugin one at a time one of them is conflicting with it and i have no plugin list from you so i cant download the plugins to test

**Comment by jerzean** [comment]
ok so its worldedit beta 01
thats a my bad on the versions i thought i had 02
https://builds.enginehub.org/job/worldedit/14715

the legacy support that is popping up in your server log will cause problems just to let you know

**Comment by dotI0** [comment]
I tryed it with only the needed plugins.

Multiverse
AWE
WE
SG

I'm using paper-1.16.1#135

Log only need pl: https://pastebin.com/YVGG0AwP

my plugin files: https://1drv.ms/u/s!AovqWqZmK_fpgdV2WVYwmGksTgvwLA?e=e1TVmu

**Comment by jerzean** [comment]
I'll look at this tonight when I get home

**Comment by dotI0** [comment]
Since last night I'm using PaperMC 1.16.2#R3. (only as information)

**Comment by dotI0** [comment]
Can you send me the working plugin files of your WE-AWE-USG-combination?
We want to play at Saturday with friends and I hope that it will work until then. :c

**Comment by jerzean** [comment]
@xManInWhitex  im just now getting time to look at this  Work has been crazy
an yea let me zip it up

**Comment by jerzean** [comment]
[SurvivalGames.zip](https://github.com/jerzean/UltimateSurvivalGames/files/5088392/SurvivalGames.zip)

**Comment by jerzean** [comment]
@xManInWhitex 
[SurvivalGames.zip](https://github.com/jerzean/UltimateSurvivalGames/files/5088392/SurvivalGames.zip)

**Comment by dotI0** [comment]
The files in the zip won't work for me either.
I've deleted the SurvivalGames folder to exclude this possibility but I can't even create an arena.

The following error occurs:
https://pastebin.com/LSrmUNUj

**Comment by xManInWhitex** [comment]
Are you testing with PaperMC?
Maybe paper is the problem?

**Comment by dotI0** [comment]
The problem must be the plugin itself. I tried it with a completely newly created paper server only with the plugin files from you and it doesn't work. (I also tested spigot not paper)

Log: https://pastebin.com/uBRZV8p6

**Comment by dotI0** [comment]
OMG my bad.
The error occurs if you want to create an arena without selecting something with worldedit. (handle it with a sg-error-msg?)
The arenas mentioned in my original post are from the old plugin from bukkit dev and they wont let me save them again with your updated plugin version. I try to create the arenas again with your updated version and let you know if it works.

Does your updated pl-version have an update announcement for your new build-releases?

**Comment by dotI0** [comment]
Okay it didn't work.

If I create a new arena the automated starting save task will work. But if I want to /sg arena save later manually the same error as in post one appears.

**Comment by jerzean** [comment]
/sg lobby unload LobbyName
/sg arena select LobbyName ArenaName.
 Then you can /sg arena save

**Comment by dotI0** [comment]
Nope it wont work this way.
Same error after "sg lobby unload" > select > save

It only works if the save task is triggered by sg arena create
