### ISSUE TITLE
Plugin not loading because there is no plugin.yml

### ISSUE THREAD

**Issue by XDRmc** [jerzean/UltimateSurvivalGames#9]
Mc Version: 1.18.2

all Plugins(and Versions): AFK-Kick*, BungeeGuard, ChatManager, Citizens, CommandPanels, Essentials, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, HolographicExtension, HolographicPlaceholders, LuckPerms, Multiverse-Core, NBTAPI, OldCombatMechanics, PlaceholderAPI, ProtocolLib, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, VoidGen, WorldGuard, WorldGuardExtraFlags (all latest versions)

Error from console: 
[20:54:28 ERROR]: Could not load 'plugins\uSurvivalGames-1.18.0002.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:202) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[pearl-1.18.2.jar:git-Pearl-"b6d3bf0"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[pearl-1.18.2.jar:git-Pearl-"b6d3bf0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[pearl-1.18.2.jar:git-Pearl-"b6d3bf0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pearl-1.18.2.jar:git-Pearl-"b6d3bf0"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

description on how to Recreate said error:

Just try loading up the plugin?

**Comment by jerzean** [comment]
no idea how i didnt catch that, ill update it when i wake up, also ill version bump it to fully support 1.18+

**Comment by XDRmc** [comment]
ok

**Comment by jerzean** [comment]
patched
